name: md2html

# This workflow is triggered on pushes to the repository
on: [ push ]

jobs:
  converttohtml:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y pandoc
      - name: Init and update submodules
        run: pandoc -f markdown --standalone --metadata title="Andrea Guarracino CV" --variable=title="" --output=index.html README.md
      - uses: actions/upload-artifact@v3
        with:
          name: README
          path: index.html
