name: README.md to index.html

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main

jobs:
  converttohtml:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - uses: docker://pandoc/core:2.9
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          # https://stackoverflow.com/questions/63928077/how-can-i-add-header-metadata-without-adding-the-h1
          args: >-  # allows you to break string into multiple lines
            -f markdown
            --standalone
            --metadata title="Andrea Guarracino CV" --variable=title=""
            --output=index.html
            README.md
      - uses: actions/upload-artifact@v3
        with:
          name: README
          path: index.html
